name: Release Build

on:
  push:
    tags:
      - 'v*' # 当推送带 v 前缀的标签时触发，如 v1.0.0

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu     # Linux x64
          - aarch64-unknown-linux-gnu    # Linux ARM64

    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: "2.1.9"

      - name: Cache Dependencies
        run: |
          deno cache --reload main.ts
          deno install

      - name: Create dist directory
        run: mkdir -p dist

      - name: Build Binary
        run: |
          deno compile --allow-net --allow-env --unstable-cron \
            --target ${{ matrix.target }} \
            --output dist/duck2api-${{ matrix.target }} \
            main.ts

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: duck2api-${{ matrix.target }}
          path: dist/duck2api-${{ matrix.target }}*

  build-alpine:
    name: Build Alpine
    runs-on: ubuntu-latest
    container:
      image: denoland/deno:alpine
    strategy:
      matrix:
        arch: [amd64, arm64]

    steps:
      - uses: actions/checkout@v4

      - name: Create dist directory
        run: mkdir -p dist

      - name: Cache Dependencies
        run: |
          deno cache --reload main.ts
          deno install

      - name: Build Binary
        run: |
          deno compile --allow-net --allow-env --unstable-cron \
            --output dist/duck2api-alpine-${{ matrix.arch }} \
            main.ts

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: duck2api-alpine-${{ matrix.arch }}
          path: dist/duck2api-alpine-${{ matrix.arch }}*

  release:
    needs: [build, build-alpine]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/**/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}