name: Release Build

on:
  push:
    tags:
      - 'v*' # 当推送带 v 前缀的标签时触发，如 v1.0.0

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
          - x86_64-pc-windows-msvc
          - x86_64-apple-darwin
          - aarch64-apple-darwin

    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: "2.1.9"

      - name: Install npm dependencies
        run: deno run -A --unstable https://deno.land/x/install_npm_deps.ts

      - name: Cache Dependencies
        run: deno cache main.ts

      - name: Create dist directory
        run: mkdir -p dist

      - name: Build Binary
        run: |
          deno compile --allow-net --allow-env --unstable-cron \
            --target ${{ matrix.target }} \
            --output dist/app-${{ matrix.target }} \
            main.ts

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ matrix.target }}
          path: dist/app-${{ matrix.target }}*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/**/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}